// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	Create_account(ctx context.Context, arg Create_accountParams) (Account, error)
	Delete_account(ctx context.Context, id int64) error
	Get_account(ctx context.Context, id int64) (Account, error)
	List_accounts(ctx context.Context, arg List_accountsParams) ([]Account, error)
	Update_accounts(ctx context.Context, arg Update_accountsParams) error
}

var _ Querier = (*Queries)(nil)
